### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/echoBot#1]
Привет, посмотрел проект, вот что надо исправить:

Не соблюдены все требования:
1. В README должно быть описание того, как разворачивать проект локально, как его запускать, должна быть описана базовая архитектура проекта так, чтобы новичкам было понятно. Всё это на английском.

2. Все настройки(токены, ответные сообщения, кол-во повторов при запуске) должны быть вынесены в конфиг. Сейчас во первых ты свои токены пушишь в репозиторий, а это очень-очень плохо, во вторых чтобы применить какие-то изменения тебе придётся заново компилировать проект.

3. В .gitignore добавить правила для папок .gitignore, .history, логов и конфига.

4. Проект должен быть скомпилирован с флагами -Wall и -Werror без ошибок.

5. Весь код должен быть проверен через hlint. У меня нашло 33 ворнинга.

Теперь по поводу кода:

1. У всего должно быть понятное имя. Например у тебя в коде есть модуль Lib и функция someFunc, надо переименовать так, чтобы было понятно, что делает someFunc и что примерно лежит в Lib.

2. Логи пишутся log-journal, при этом есть файл log-journal.txt. Писать надо во второй, первый удалить.

3. Оставлять за собой закомментированный код нельзя. Если очень надо, то рядом надо написать причину.

4. В некоторых местах ты используешь для отступа 4 пробела, а в некоторых 2. Необходимо придерживаться единого стиля по всему проекту. Рекомендую 2 пробела, т. к. мы используем 2. Также если имя содержит несколько слов, то где-то ты разделяешь их нижним подчёркиванием, а где-то каждое последующее слово начинается с заглавной буквы. Здесь также нужно выбрать единый стиль(рекомендую второе).

5. Постарайся писать более информативные сообщения для коммитов. Например, увидел сообщение "l" или сообщение "1-test". Лучше писать "fixed VK tests" или "added Telegram tests".

6. Есть неочевидные сокращения и ошибки в словах, постарайся избавиться от этого. Например "Mess"(лучше "Msg") или "loging"(правильно "logging").

**Comment by Sergey111991KV** [comment]
Извиняюсь за столько не почётов - спешил просто)
По требованиям:
1. В README добавил полезной информации - все на английском, но могут быть конечно ошибки в словах - я работаю над этим.
 И тут сразу вопрос по поводу разворачивания - у меня не работает getEnv: does not exist (no environment variable) - я так подозреваю это из-за системы, потому что создаются переменные и они даже проходили, но почему то прекратилось...
2. Конфиги убрал из репозитория, сделал две версии запуска - стандартный и с внесением непосредственно в процессе.
3. В .gitignore добавил файлы - вроде достаточно, но я с этим не сталкивался на больших проектах, поэтому убрал все журналы и текстовые файлы на всякий случай.
4. Про эти флаги блин я вообще не понял)) - подумал что это просто стандартная компиляция) - кое какие замечания остались, они в файле Lib - но я написал и думаю это не критично, не пойму просто почему не работает от предложенных изменений.
5. Hlint все проверил - просто до этого не проверял папку тестов, дописывал и не проверил к сожалению.
По коду:
1. Функции исправил в Lib - перечитал документацию по наименованию, верблюжьему стилю и т.п. Был просто под влиянием некоторых проектов, где логи в функциях просто отправляют как l - одной буквой.
2. Журнал удалил, добавил еще один для тестов.
3. Убрал закоментированный код - мне жалко было его просто удалять) есть программа куда можно все заносить - с тегами и поддерживаемым синтаксисом, буду стараться туда сразу убирать. Понимаю что закоментированный код отвлекает и раздражает - не думал об этом просто(
4. Стараюсь везде придерживаться верблюжьего стиля - только где скопировал код, там идет через подчеркивание, исправлю где найду. Пробелы выставлял Hspec - скорее всего 4 пробела в тестах - все прошел вроде им и должен быть один стиль.
5. Комментарии - да это моя лень, понимаю их необходимость во всем, даже в обычных примерах данных для сервера - так информативнее и приятнее читать, чем просто "test1" "test2".
6. Английский подтягиваю, по правилам сокращений - у всех они разные, но я буду делать как скажешь, а то режет глаз не спорю. Ошибки с logging и Update исправил))

**Comment by olegromashin** [comment]
То что сделал запуск через переменные системы это хорошо, но у нас требование, что должен быть конфиг) И опять же, если захочешь поменять текстовые ответы на команды, то придётся перекомпилировать проект, что не есть хорошо. Представь, что бота надо запустить на какой-то другой машине. Пользователю придётся клонировать репозиторий, качать все зависимости и компилировать.
Можешь создать шаблон конфига, который будет в репозитории. Например вот так:
1. Создать папку templates в корне проекта и туда положить незаполненный конфиг bot.config.template.
2. Написать в README что для запуска проекта надо скопировать bot.config.template к исполняемому файлу, переименовать в bot.config и заполнить.
3. Добавить правило для файлов *.config, чтобы заполненные конфиги не пушить.

Hlint по-прежнему выдаёт кучу ворнингов, можешь прогнать его на всём проекте так: hlint echoBot
Предварительно подняться на уровень из корня проекта, конечно.

В gitignore у тебя лишнее правило для my-token.txt, на пятой строчке уже есть правило.

В некоторых местах ещё есть закомментированный код без пояснений, можешь в поиске набрать "--" и увидишь. Также есть лишние комментарии, например "-- logging" напротив логирования, можно просто взглянуть на строку и понять, что это логирование. Помимо этого функции логирования ты дал имя "LogIn", в английском у этого выражения другое значение, лучше переименовать в "writeLog" или что-нибудь типа того.

В целом молодец, очень круто, что так быстро исправил большинство недочётов)

**Comment by Sergey111991KV** [comment]
Сделал папку template и добавил туда файл импортируемый с проектом, добавил исключения в gitignore как и написал ты) 
Hlint - проверил папки src и test, осталось 2-3 ворнинга, которые нужно исправить посредством или изменения функций или добавления новой - но опять же есть ли смысл? если есть больше ворнингов - я не понимаю как проверить, у меня весь корневой проект не проверяется(
gitignore - я просто не пользовался этим к сожалению, поэтому изучаю и изменил правила.
Убрал закомментируемый код - он действительно сбивает, по поводу названий - думаю что это уже от команды зависит и от стиля написания - просто бывает  получаются названия из 3-4 слов, в некоторых я так понял это норм - в некоторых стараются принимать более короткие. Тут уже как мне кажется нужно следовать правилам команды)  Неправильно написанные - бывает, не спорю - но такое сразу не видится, если глаз не наметан. Исправил то что нашел.

**Comment by olegromashin** [comment]
Добавь ещё в конфиг изначальное кол-во повторов и сообщения ответные от бота, такое тоже должно настраиваться)

**Comment by olegromashin** [comment]
Прошёлся по проекту ещё раз.

Опять напишу, что стоит поработать над именованием:
Есть рекорд `v :: VKConfig -> Double` , постарайся дать такое имя, чтобы было понятно назначение этого поля.
Также в конфиге есть рекорды `sendMessage` и `lastMessId` . Нужно стараться придерживаться одного стиля, особенно, когда эти имена так близко. В обоих рекордах или сокращать слово "message" , или не сокращать. В английском у слова "mess" другое значение, поэтому, если будешь сокращать, то используй "msg".

В README проекта надо сделать понятное описание того, как работать с конфигом: скопировать bot.config.template, положить в корень проекта, заполнить конфиг данными.

После того, как я вписал свой telegram-токен я получаю вот такой вывод:
```
CannotGetConfig
"wrong telegram token"
CannotGetConfig
CannotGetConfig
CannotGetConfig
```

**Comment by Sergey111991KV** [comment]
Подошел с другой стороны к переименованию файлов - создал отдельный проект, где буду добавлять правила наименования всех сущностей - https://github.com/Sergey111991KV/WorkingRules, поэтому буду туда добавлять по мере необходимости.
Извиняюсь за конфиг - сделал более понятным, если нет - тогда буду еще пробовать на примерах
