### ISSUE TITLE
имплементация tryGetCountRepeat

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/echoBot#12]
в `Adapter.Tel.TelEchoBot` и `Adapter.VK.VKEchoBot` tryGetCountRepeat практически одинаковые, стоит их вынести. А так же стрнное вычисление ответа через lookup. Почему бы просто не делать `readMaybe msg`, а затем проверять чтобы 0 < n <= 5?

**Comment by Sergey111991KV** [comment]
сделал
