### ISSUE TITLE
Дублирующийся код

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/echoBot#13]
В `src.Adapter.VK.VKBot.getMsgLast` обе ветви `case tsLast . longConfig $ config st of` на 99% одинаковы.
Там же рядом `getInitialConfig` и `getWithOldConfig` на 80% одинаковы
В `Bot.Bot` все три функции на 90% одинаковы

**Comment by Sergey111991KV** [comment]
Эти функции изменил, а некоторые просто удалил - не нужная абстракция, просто когда обдумывал бота - разделил все на действия и заполнял по мере
