### ISSUE TITLE
Парсинг сообщения ВК

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/echoBot#14]
Есть `instance FromJSON MessageVK` с парсингом через массив, почему так?
Этот же функционал дублируется в `Adapter.VK.VKBot.parseArray`

**Comment by ghost** [comment]
При этом в логе постоянно повторятся ошибка:
```
Error parseArrays VK
VK getMsgLast CantConvertFromData
```

**Comment by Sergey111991KV** [comment]
Так как у ответа vk был массив сообщений, причем разных - то я сделал этот парсинг через массив, instance FromJSON MessageVK - был уже лишним не спорю и сообщение поменял на отсутсвие новых сообщений, хотя лучше сделать через fromjson - только нужно разобраться с парсингом вложенного массива

**Comment by ghost** [comment]
Ничего не понимаю, ведь сообщение вк это [объект](https://vk.com/dev/objects/message),  с вполне определенными полями, имеющими название, а не массив

**Comment by Sergey111991KV** [comment]
В общем и в целом - я руководствовался этой статьей - https://habr.com/ru/post/335106/ - там приходит массив абсолютно всех событий, вплоть до друзей онлайн - поэтому вот такой ответ у меня обычно: responseBody = "{\"ts\":1683050329,\"updates\":[[4,1735,17,442266618,1608304395,\" ... \",\"тест\"]]}\r\n" - а если в этом массиве будет еще что нибудь? да я понимаю, что нужно сделать все красивее, но я руководствовался этим, поэтому и работало

**Comment by ghost** [comment]
Ага, оказывается это [апи для пользователей](https://vk.com/dev/using_longpoll) (т.е. для фронтендов вк: приложений на айос, андроид..). Есть отдельное [апи для ботов](https://vk.com/dev/bots_longpoll), там событие это "нормальный" [объект](https://vk.com/dev/groups_events), а не [массив](https://vk.com/dev/using_longpoll_2?f=3.%2B%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%2B%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9)
> В противоположность User Long Poll, Bots Long Poll API работает с событиями сообщества, а не пользователя.

В таком случае, нужно фильтровать события по коду 4 (как я понял), я этого не нашел, а алгоритм парсинга `parseArrays` таков: прочитать последние 7 элемента массива и положить их по порядку в `MessageVK`

**Comment by Sergey111991KV** [comment]
Ну да, я в принципе так и делал - https://stackoverflow.com/questions/24742872/how-to-parse-an-array-with-haskell-aeson - просто трудно было выразить с выводами и прочим, решил сделать функцию прямо там, а еще проверял не по коду, а по длине - хотя по коду надежнее конечно, но там как я понял фиксированный размер у всех

**Comment by Sergey111991KV** [comment]
Сделал
