### ISSUE TITLE
Самостоятельная работа модулей

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/echoBot#17]
При отсутствии одного из токенов, другой модуль продолжает работать. В случае с неработающим вк это спамящиеся раз в секунду сообщения `NotAnswer VK`, в случае с неработающей телегой это `NotAnswer Telegram` и огромные сообщения `HttpExceptionRequest`

**Comment by Sergey111991KV** [comment]
это не доработал новую архитектуру, исправил
