### ISSUE TITLE
Пофиксить импорты в тестах

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/echoBot#2]
https://github.com/Sergey111991KV/echoBot/blob/master/test/Bot/BotSpec.hs#L8

https://github.com/Sergey111991KV/echoBot/blob/master/test/Bot/EchoBotSpec.hs#L11

Надо поправить импорты)

**Comment by Sergey111991KV** [comment]
Да как так то.... блин это все не внимательность - вижу только два пути выхода отсюда: 
или взять за привычку сразу делать ghci build, а потом ghci  test 
или как начинаю работать с проектом запускать тесты в фоновом режиме, я просто команды эти не знал
ну или возможно, сейчас прохожу по js, можно ли создать команды в запуске, чтобы было сначала build а потом test?
 Так то конечно пофиксил, но это время... Олег уже 10 раз проверил проект :))) я перед ним в долгу уже)))
