### ISSUE TITLE
Зависимости

### ISSUE THREAD

**Issue by catdarick** [Sergey111991KV/echoBot#3]
Все ли зависимости используются и необходимы?
Сборка с нуля достаточно долгая, стоит проверить этот момент, возможно тут есть лишние пакеты
https://github.com/Sergey111991KV/echoBot/blob/2ebb8bdeec342e95ae92e767fa8834bdb2974899/package.yaml#L22

**Comment by Sergey111991KV** [comment]
Я боялся что могут быть лишние зависимости, поэтому старался добавлять все по мере ошибки - если она есть, то добавляю, дело как я предполагаю в другом - classy-prelude... это в общем почти та же самая prelude, только с заточенной работой для Text and Bytestring, хотя в некоторых местах из-за не знания и не полного ее использования приходилось пользоваться старой Prelude, что не есть хорошо. 
 Если проблема в этом, то или отказаться от нее полностью или же доучить ее мне и смириться с ее весом. Если же проблема не в этом... тогда я не знаю - писать код без этих зависимостей(
