### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by catdarick** [Sergey111991KV/echoBot#4]
Здесь функции возвращают тип с ошибкой, но ошибки игнорируются, не стоит так делать.
Если ошибки обрабатываются в самих функциях, то они не должны возвращать те же самые ошибки
https://github.com/Sergey111991KV/echoBot/blob/2ebb8bdeec342e95ae92e767fa8834bdb2974899/src/Bot/EchoBot.hs#L99-L106

**Comment by Sergey111991KV** [comment]
Правда не подумал про логику здесь, сами возвращаемые ошибки говорят что нужно делать дальше, а я подумал будет просто достаточно перезагрузить эту функцию. Возможно нужно еще один модуль написать для ручной перезагрузки бота после исправления ошибки в написании конфига или интернет соединения
