### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by catdarick** [Sergey111991KV/echoBot#5]
Должен быть единый стиль именования.
На участке кода, предоставленном ниже, я насчитал 4 различных представления `message` :)
https://github.com/Sergey111991KV/echoBot/blob/2ebb8bdeec342e95ae92e767fa8834bdb2974899/src/Bot/EchoBot.hs#L56-L72

**Comment by Sergey111991KV** [comment]
Блин я не знаю как это получается, нет правда - может просто этот код сам писал и глаза затуманены? я везде щас исправлю этот message где только возможно...
