### ISSUE TITLE
Непонятные название переменных

### ISSUE THREAD

**Issue by catdarick** [Sergey111991KV/echoBot#6]
`txt` - слишком уж общее название. 
https://github.com/Sergey111991KV/echoBot/blob/2ebb8bdeec342e95ae92e767fa8834bdb2974899/src/Bot/EchoBot.hs#L59
То есть на этой строке
https://github.com/Sergey111991KV/echoBot/blob/2ebb8bdeec342e95ae92e767fa8834bdb2974899/src/Bot/EchoBot.hs#L84
совсем не понятно что за строка у нас получится в результате.
Нужно пройтись по обоим проектам и посмотреть, достаточно ли информативны названия

**Comment by Sergey111991KV** [comment]
Я просмотрел некоторые проекты просто - там вообще опции сводили чуть ли не к буквам, есть еще много статей про названия переменных - как я понял это почти холиварная тема (это слово я тоже узнал из этих статей), так как одни говорят, что название функции само говорит за себя и использование переменных больше нигде не будет встречаться, другие наоборот говорят о большей информативность, не смотря на увеличивающиеся названия... я сам когда читаю слово где больше 3 camelCase -уже глаз дергается, оптимально 2-3 для меня. В любом случае - пройдусь и исправлю!

**Comment by catdarick** [comment]
Лучше давать понятные имена, чтобы не приходилось искать место, где им присваиваются значения)


По поводу практик именования: для меня не совсем понятны мотивы разработчиков, которые сводят названия к буквам. 
Пример, с которым сам накануне столкнулся:
![image](https://user-images.githubusercontent.com/48927343/99519364-da5e8380-29a2-11eb-94bf-8e37c90f05ff.png)
Это функция для проверки подписи в одной из библиотек, последние два аргумента - два `ByteString`, никакого описания нету, в один из них нужно поместить сообщение, в другой подпись. Но как понять что куда положить? Обычно это решается быстрым осмотром исходников, но в этом случае разработчик оказался практикующим короткие названия, и в исходниках я вижу это:
![image](https://user-images.githubusercontent.com/48927343/99519977-96b84980-29a3-11eb-979f-6db27dff7e54.png)
Что тут подразумевается под `m` и `sm` не совсем понятно: если `m` == `message`, то `sm` == `signed message`? (нет, это оказалось не так.) Можно еще взглянуть на последнюю строку -- `ep pk sm` это вообще что? 
Создается такое чувство, что пишется такой код с намерением сделать его поддержку невозможной :)

**Comment by Sergey111991KV** [comment]
Не ну здесь понятно, что ничего не понятно) в идеале конечно и Bytestring можно поменять на свои типы -  Message and SignedMessage) Когда сам пишешь - тебе все понятно где что, а вот проверяющим... я подумал что это тестовый проект и здесь не нужно это все, я понял что был не прав. В итоге: 
   короткие переменные изменяю по примеру txt ++ (чей текст?) Msg ++  (есть ли какие особые условия?) ++ Edit -- for example.
 Вопрос, если только в разных функциях используется  txtMsg - тот же  send or get - можно ли там использовать одно название переменной или же чтобы не искать эту переменную в каком месте кода она стоит изменить ее сразу на txtMsgSend and txtMsgGet?

**Comment by catdarick** [comment]
> Вопрос, если только в разных функциях используется txtMsg - тот же send or get - можно ли там использовать одно название переменной или же чтобы не искать эту переменную в каком месте кода она стоит изменить ее сразу на txtMsgSend and txtMsgGet?

Не нужно добавлять суффиксы именам (референсы к названиям функций), если смысл и так понятен из контекста. В данном случае он понятен

> В итоге:
> короткие переменные изменяю по примеру txt ++ (чей текст?) Msg ++ (есть ли какие особые условия?) ++ Edit -- for example.

А вот этот вопрос я не понял, что-то..

**Comment by Sergey111991KV** [comment]
Ну в двух функции возвращается текст и если я его и там и там назову - txt, как я понял это будет не очень? и чтобы как то систематизировать где какой текст будет возвращаться - где будет от сообщения, где-то может описание юзера, а где-то юзера - но только не описание, а скажем имя - решил просто сделать правила на будущее для себя как называть) есть же общие договоренности? скажем в js - там сначала идет имя метода, потом где он находится или для чего, а потом скажем что скажем или общее что-то что объединяет все файлы в этой папке) в общем просто правила

**Comment by catdarick** [comment]
Нужно называть так, чтобы название описывало сущность
Например:
*  `let txt = getMessageTextFromUpdate` - плохое название
 `let userMessage = getMessageTextFromUpdate` - нормальное 
`txt` - не даёт никакой информации о том, что лежит в этой переменной, а говорит лишь о её типе.
* `txt <- getNameAdapter` - плохое название
`adapterName <- getNameAdapter` - нормальное 

В таком случае заместо упомянутой в ишью строки будет 
 `writeLog Debug (adapterName ++ " tryGetCountRepeat is done ")`
, что даёт возможность не искать место определения, а просто читать код

**Comment by Sergey111991KV** [comment]
Ок, понял)
