### ISSUE TITLE
Неудачное название для класса

### ISSUE THREAD

**Issue by catdarick** [Sergey111991KV/echoBot#7]
Название класса не совсем коррелирует с назначением и только путает, на мой взгляд
`BotCompatibleMessage` или просто `BotMessage` подойдут лучше
https://github.com/Sergey111991KV/echoBot/blob/2ebb8bdeec342e95ae92e767fa8834bdb2974899/src/Bot/Message.hs#L9

**Comment by Sergey111991KV** [comment]
Переименовал на BotMessageGetOption

**Comment by catdarick** [comment]
Тоже не совсем удачное название.
Названия классов должны как-то характеризовать объект: либо описывать его сущность целиком, либо какое-то из свойств. 
То есть в случе если написан контекст `BotCompatibleMessage a`, мы читаем это как: тип `a` должен быть сообщением и совместим с ботом. 
`BotMessageGetOption a` прочитать похожим образом не получается -- название больше подходит для функции, так как описывает действие

**Comment by Sergey111991KV** [comment]
Классы выражают общее свойство - такие как Eq, Show - типа compatible - должно говорить о свойстве того, что его реализует, а Get - большинство функций начинаются с этого...  А можно ли Делать имена классов  как я в сервере сделал - CommonServise например или тот же EchoBot - это получается как набор методов для реализации необходимого функционала? они же говорят, что объект реализует именно это свойство?

**Comment by catdarick** [comment]
Да, EchoBot в контексте задания - нормальное название, CommonService тоже

**Comment by Sergey111991KV** [comment]
Переименовал на BotCompatibleMessage)
