### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by catdarick** [Sergey111991KV/echoBot#8]
Не совсем понимаю назначение `To` в названиях. 
Если смотреть на вызов функции не видя сигнатуры, то кажется, что нужено передать аргументом id назначение
https://github.com/Sergey111991KV/echoBot/blob/2ebb8bdeec342e95ae92e767fa8834bdb2974899/src/Bot/Bot.hs#L28

**Comment by Sergey111991KV** [comment]
Логика была такой: To - предлог к чему-то, куда то -   поэтому отправка сообщения куда-то... Без нее проще и понятнее, не спорю
